name: 'social_media_analytics'
version: '1.0.0'
config-version: 2

profile: 'social_media_analytics'

model-paths: ["models", "sources"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  social_media_analytics:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts