name: 'social_media_analytics'
version: '1.0.0'
config-version: 2

profile: 'social_media_analytics'

model-paths: ["models", "sources"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  social_media_analytics:
    staging:
      +schema: silver
      +materialized: view
    intermediate:
      +schema: silver
      +materialized: incremental
    marts:
      +schema: gold
      +materialized: table

vars:
  "dbt_date:start_date": "2024-01-01"
  "dbt_date:end_date": "2030-12-31"